apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-logs-pvc
  namespace: php-app1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
  storageClassName: alicloud-disk-ssd
