name: CI-CD DockerHub App PHP

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test_kube:latest -f docker_prism/dev/etc/Dockerfile docker_prism/dev/etc

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test_kube:latest
